[metadata]
description-file = "README.md"

[build-system]
requires = ["poetry>=1.0", "coverage[toml]"]
build-backend = "poetry.masonry.api"


#########################################################################################
# Poetry metadata
#########################################################################################

[tool.poetry]
name = "chembler"
version = "0.0.1"
description = "Boil down ChEMBL annotations."
include = [
	"README.md",
	"CHANGELOG.md",
	"LICENSE.txt"
]
authors = ["Douglas Myers-Turnbull"]
maintainers = ["dmyersturnbull"]
keywords = ["chembl", "targets", "activity", "pipeline", "cheminformatics"]
homepage = "https://github.com/dmyersturnbull/chembler"
repository = "https://github.com/dmyersturnbull/chembler"
documentation = "https://chembler.readthedocs.io"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Natural Language :: English",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
	"Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Environment :: Console",
    "Topic :: Scientific/Engineering :: Chemistry",
]

[tool.poetry.urls]
build = "https://github.com/dmyersturnbull/chembler/actions"
issues = "https://github.com/dmyersturnbull/chembler/issues"
source = "https://github.com/dmyersturnbull/chembler"


#########################################################################################
# Tyrannosaurus
#########################################################################################

[tool.tyrannosaurus.options]
align = true

[tool.tyrannosaurus.sources]
# use a literal value ('') or refer to a pyproject setting
# ${today} is the date you run it at, and ${now} is the datetime
status             = "'Development'"
date               = "'${today}'"
copyright          = "'Copyright ${today.year}'"
version            = "tool.poetry.version"
release            = "tool.poetry.version"
pyversions         = "tool.poetry.dependencies"
devdeps            = "tool.poetry.dev-dependencies"
linelength         = "tool.black.line-length"
# comma-separated
maintainers        = "'dmyersturnbull'"

[tool.tyrannosuarus.paths]
recipe             = "'recipes/${name}/meta.yml'"
environment        = "'environment.yml'"

[tool.tyrannosaurus.targets]
# these are file and directory names, without filename extensions
pyproject    = true
init         = true
tox          = true
docs         = true
recipes      = true
environment  = true
license      = true
authors      = true
github       = true
travis       = true
dockerfile   = true
readme       = true
changelog    = true


#########################################################################################
# Poetry build & dependencies
#########################################################################################

[tool.poetry.scripts]
chembler = "chembler.cli:cli"

[tool.poetry.dependencies]
python                     = "^3.8"
tomlkit                    = "^0.6"
importlib-metadata         = "^1.6"
typer                      = "^0.2"
requests                   = "^2.23"
chembl-webresource-client  = "^0.10"

[tool.poetry.dev-dependencies]
tyrannosaurus            = ">=0.4,<1.0"
pre-commit               = "^2.3"
pytest                   = "^5.4"
coverage                 = {extras = ["toml"], version = "^5.1"}
pytest-cov               = "^2.8"
sphinx                   = "^3.0"
sphinx-autoapi           = "^1.3"
sphinx-rtd-theme         = "^0.4.3"
mypy                     = "^0.750"
flake8                   = "^3.7"
flake8-docstrings        = "^1.5"
black                    = "=19.10b0"
isort                    = "^4.3"
sphinx-autodoc-typehints = "^1.10"
xdoctest                 = "^0.12"
hypothesis               = "^5.10"
flake8-bandit            = "^2.1"
flake8-bugbear           = "^20.1"


[tool.poetry.extras]
# auto-filled from dev-deps
dev     = [
        "tyrannosaurus"
]

#########################################################################################
# Style checking
#########################################################################################

[tool.coverage.paths]
source = ["chembler"]

[tool.coverage.run]
source = ["chembler"]

[tool.coverage.report]
show_missing = true

[tool.black]
line-length = 100
target-version = ["py36", "py37", "py38"]

[tool.isort]
line_length = 100
[mypy]
check_untyped_defs = true
strict_optional = true

[pycodestyle]
max-line-length = 100
statistics = true

[pydocstyle]
# 212 and 213 contradict; 203 and 204 contradict; D302 is not relevant in Py3
ignore = ["D203", "D212", "D302"]