# Build, test, and run static analyses, and send reports to external services
# Runs only on pushing to main
name: Build & test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version:
          - 3.9
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install build meta-dependencies
        run: |
          pip install poetry tox
      - name: Test with tox
        run: |
          tox -v
      - name: Build the Docker image
        run: |
          docker build .
      - name: Update coveralls/codecov
        run: |
          pip install coveralls codecov
          coveralls || true
          codecov || true
